### ISSUE TITLE
Making and prioritizing Issues

### ISSUE THREAD

**Issue by mwichrowski** [de-haagse-hogeschool/grzegorz-brzeczyszczykiewicz-apde#1]
We need to make and prioritize all the issues for this project 😄

**Comment by Pawel-Zawada** [comment]
I raised issues for all requirements for put forward by our assignment document, under the heading **Opdracht 1.**

[Casus Console Drawing v 10.pdf](https://github.com/de-haagse-hogeschool/grzegorz-brzeczyszczykiewicz-apde/files/3051504/Casus.Console.Drawing.v.10.pdf) - Reference **Opdracht 1**
