### ISSUE TITLE
Draw initial class diagram for the code's structure design

### ISSUE THREAD

**Issue by Pawel-Zawada** [de-haagse-hogeschool/grzegorz-brzeczyszczykiewicz-apde#2]
Teken het volledige klassendiagram uit in Visual Paradigm, dus met alle attributen,
constructors en methodes en gespecificeerd met types en de volledige parameterlijst.

**Uitzondering**: je mag de setters en de getters weglaten. Die voegen weinig informatie toe en
zo blijft het diagram overzichtelijk.

**Criterium**: je klassendiagram is volledig uitgewerkt als je het (althans: in principe) zonder
toelichting aan een programmeur kunt geven zodat die het 1-op-1 kan vertalen in
programmacode.

**Comment by mikolajwichrowski** [comment]
Ik heb voor nu een probeersel gemaakt. Deze moet worden besproken en eventuele opmerkingen moeten worden verwerkt.
![E10F0445-9A12-4C51-B828-A33F73313580](https://user-images.githubusercontent.com/23257783/55684103-dace1600-5947-11e9-9cd7-5b1ca2f3822d.png)

**Comment by Pawel-Zawada** [comment]
Resolved by:
https://github.com/de-haagse-hogeschool/grzegorz-brzeczyszczykiewicz-apde/wiki/Class-Diagram

**Further updates will be raised in new issues.**

**Comment by mikolajwichrowski** [comment]
New complete version!
![1469858C-8482-479F-925F-DB27862F7295](https://user-images.githubusercontent.com/23257783/56082936-20df1a00-5e1f-11e9-8b2f-3c716d3da127.jpeg)
