### ISSUE TITLE
Implement `fill()` method to the Quadrilateral class

### ISSUE THREAD

**Issue by Pawel-Zawada** [de-haagse-hogeschool/grzegorz-brzeczyszczykiewicz-apde#3]
Gebruik de methodes fillPixel(…) en clearPixel(…) die al zijn gedefinieerd in Shape.

**Comment by mikolajwichrowski** [comment]
Verzoek om de benaming te doen op wetenschappelijke manier. Een `rectangle` heeft in theorie altijd een gelijke lengte een hoogte. Een `quadrilateral` heeft een algemenere beschrijving en past beter bij de casus.

**Comment by Pawel-Zawada** [comment]
> Verzoek om de benaming te doen op wetenschappelijke manier. Een `rectangle` heeft in theorie altijd een gelijke lengte een hoogte. Een `quadrilateral` heeft een algemenere beschrijving en past beter bij de casus.

`quadrilateral` is al zo te zien al verwerkt in #2, geïmplementeerd in 6f6093c.

**Geen verdere actie verreist.**

**Comment by Pawel-Zawada** [comment]
Moet `fillPixel()` gebruiken om daadwerkelijk volgens model het verwachtte gedrag te krijgen.

**TODO**
- [ ] Implement `fillPixel()` in `Quadrilateral` class
